### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "test user",
  "email": "test@example.com",
  "password": "password123",
  "phone": "0764175336",
  "role": "family"
}
### login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Auth Token after login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODQyZWI0NDdkMTMwY2U0NDYzMThjM2QiLCJyb2xlIjoiZmFtaWx5IiwiaWF0IjoxNzQ5NDY3MDY4LCJleHAiOjE3NDk1NTM0Njh9.equS4AdO3bFLO8XIrnAvrpFwsf3U-CHfQr7Ee7wvBIw

#***************** Device API  *****************#
### Register new Device
POST http://localhost:5000/api/devices
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "macAddress": "AC23VF12NBHg",
  "owner": "test user",
  "name": "laptop",
  "deviceId": "123444h"
}

### Get Device info => id
GET http://localhost:5000/api/devices/6846c300635333ea0d2bd0ea
X-Auth-Token: {{token}}

### Get Device health data => id
GET http://localhost:5000/api/devices/6846c300635333ea0d2bd0ea/health
X-Auth-Token: {{token}}

#***************** Emergency Alerts API  *****************#
### Get Emergencies data
GET http://localhost:5000/api/emergencies
X-Auth-Token: {{token}}

### Get Specific Emergency data => id
GET http://localhost:5000/api/emergencies/6842f184c901f22f2c4b503e
X-Auth-Token: {{token}}

### Update Emergency data => id
PUT http://localhost:5000/api/emergencies/6842f184c901f22f2c4b503e/status
X-Auth-Token: {{token}}

#***************** Health Data API  *****************#

### Get Health data => deviceId
GET http://localhost:5000/api/health/6842f184c901f22f2c4b503e
X-Auth-Token: {{token}}

### Get Health Summary => deviceId
GET http://localhost:5000/api/health/6842f184c901f22f2c4b503e/summary
X-Auth-Token: {{token}}